// Code generated by "so test". DO NOT EDIT.

package main

import "solod.dev/so/testing"

func main() {
	testing.RunTests("so/unicode", []testing.Test{
		{Name: "TestIs", F: TestIs},
		{Name: "TestTo", F: TestTo},
	})
}
