package compiler

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
	"unicode/utf8"
)

// runnerName is the file name of the runner emitted into the test dir.
// It carries a DO NOT EDIT header and is regenerated on every `so test`.
const runnerName = "main.go"

// Test discovers TestXxx functions in the "test" subdirectory of srcDir,
// generates a deterministic main.go runner there, and runs it via Run.
func Test(srcDir string, opts Options) error {
	testDir := filepath.Join(srcDir, "test")
	info, err := os.Stat(testDir)
	if err != nil || !info.IsDir() {
		return fmt.Errorf("no test directory: %s", testDir)
	}

	names, err := findTests(testDir)
	if err != nil {
		return err
	}
	if len(names) == 0 {
		return fmt.Errorf("no TestXxx functions found in %s", testDir)
	}

	if err := writeRunner(testDir, packageName(srcDir), names); err != nil {
		return err
	}

	return Run(testDir, nil, opts)
}

// findTests parses every non-generated .go file in dir and returns the sorted
// names of functions matching `func TestXxx(t *testing.T)`.
func findTests(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	fset := token.NewFileSet()
	var names []string
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || name == runnerName {
			continue
		}
		path := filepath.Join(dir, name)
		file, err := parser.ParseFile(fset, path, nil, 0)
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", path, err)
		}
		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Recv != nil || !isTestName(fn.Name.Name) {
				// Non-TestXxx function, silently skip it.
				continue
			}
			// A function that looks like a test but has the wrong signature is
			// almost always a mistake, so reject it loudly rather than skipping it.
			if err := checkTestSig(fn); err != nil {
				return nil, fmt.Errorf("%s: %w", path, err)
			}
			names = append(names, fn.Name.Name)
		}
	}

	sort.Strings(names)
	return names, nil
}

// packageName returns a human-readable name for the package under test,
// used in the test summary line. It is the cleaned source path (e.g.
// "so/sync"), falling back to the current directory's base name for ".".
func packageName(srcDir string) string {
	pkg := filepath.ToSlash(filepath.Clean(srcDir))
	if pkg == "." {
		if abs, err := filepath.Abs(srcDir); err == nil {
			pkg = filepath.Base(abs)
		}
	}
	return pkg
}

// isTestName reports whether name is a valid test name: "Test" optionally
// followed by a suffix that does not start with a lowercase letter. This
// mirrors Go's own rule, so a helper like "Testhelper" is not run as a test.
func isTestName(name string) bool {
	if !strings.HasPrefix(name, "Test") {
		return false
	}
	if len(name) == len("Test") {
		return true
	}
	r, _ := utf8.DecodeRuneInString(name[len("Test"):])
	return !unicode.IsLower(r)
}

// checkTestSig verifies that fn, whose name already qualifies
// as a test, has the signature `func(t *testing.T)`.
func checkTestSig(fn *ast.FuncDecl) error {
	want := fmt.Sprintf("test %s must have signature func(t *testing.T)", fn.Name.Name)
	if fn.Type.TypeParams != nil {
		return fmt.Errorf("%s: it must not be generic", want)
	}
	if fn.Type.Results != nil {
		return fmt.Errorf("%s: it must not return a value", want)
	}
	if !isTestingTParam(fn.Type.Params.List) {
		return fmt.Errorf("%s", want)
	}
	return nil
}

// isTestingTParam reports whether params is
// a single parameter of type *testing.T.
func isTestingTParam(params []*ast.Field) bool {
	// A single field may still declare multiple names, e.g. func(a, b *T).
	if len(params) != 1 || len(params[0].Names) > 1 {
		return false
	}
	star, ok := params[0].Type.(*ast.StarExpr)
	if !ok {
		return false
	}
	sel, ok := star.X.(*ast.SelectorExpr)
	if !ok {
		return false
	}
	pkg, ok := sel.X.(*ast.Ident)
	return ok && pkg.Name == "testing" && sel.Sel.Name == "T"
}

// writeRunner emits the generated main.go that dispatches the given tests
// for package pkg.
func writeRunner(dir, pkg string, names []string) error {
	var b strings.Builder
	b.WriteString("// Code generated by \"so test\". DO NOT EDIT.\n\n")
	b.WriteString("package main\n\n")
	b.WriteString("import \"solod.dev/so/testing\"\n\n")
	b.WriteString("func main() {\n")
	fmt.Fprintf(&b, "\ttesting.RunTests(%q, []testing.Test{\n", pkg)
	for _, name := range names {
		fmt.Fprintf(&b, "\t\t{Name: %q, F: %s},\n", name, name)
	}
	b.WriteString("\t})\n")
	b.WriteString("}\n")

	path := filepath.Join(dir, runnerName)
	return os.WriteFile(path, []byte(b.String()), 0o644)
}
