// Code generated by "so test". DO NOT EDIT.

package main

import "solod.dev/so/testing"

func main() {
	testing.RunTests("so/net", []testing.Test{
		{Name: "TestJoinHostPort", F: TestJoinHostPort},
		{Name: "TestSplitHostPort", F: TestSplitHostPort},
		{Name: "TestTCP_AcceptDeadline", F: TestTCP_AcceptDeadline},
		{Name: "TestTCP_ClearDeadline", F: TestTCP_ClearDeadline},
		{Name: "TestTCP_CloseErrors", F: TestTCP_CloseErrors},
		{Name: "TestTCP_Dial", F: TestTCP_Dial},
		{Name: "TestTCP_DialRefused", F: TestTCP_DialRefused},
		{Name: "TestTCP_Listen", F: TestTCP_Listen},
		{Name: "TestTCP_ListenAll", F: TestTCP_ListenAll},
		{Name: "TestTCP_ReadDeadline", F: TestTCP_ReadDeadline},
		{Name: "TestTCP_ReadEOF", F: TestTCP_ReadEOF},
		{Name: "TestTCP_ResolveFamilyMismatch", F: TestTCP_ResolveFamilyMismatch},
		{Name: "TestTCP_ResolveHostname", F: TestTCP_ResolveHostname},
		{Name: "TestTCP_ResolveNamedPort", F: TestTCP_ResolveNamedPort},
		{Name: "TestUDP_CloseErrors", F: TestUDP_CloseErrors},
		{Name: "TestUDP_Dial", F: TestUDP_Dial},
		{Name: "TestUDP_Listen", F: TestUDP_Listen},
		{Name: "TestUDP_ReadDeadline", F: TestUDP_ReadDeadline},
		{Name: "TestUDP_ReadFromWriteTo", F: TestUDP_ReadFromWriteTo},
		{Name: "TestUDP_ResolveAddr", F: TestUDP_ResolveAddr},
		{Name: "TestUnix_CloseErrors", F: TestUnix_CloseErrors},
		{Name: "TestUnix_Datagram", F: TestUnix_Datagram},
		{Name: "TestUnix_DialRefused", F: TestUnix_DialRefused},
		{Name: "TestUnix_ReadDeadline", F: TestUnix_ReadDeadline},
		{Name: "TestUnix_Resolve", F: TestUnix_Resolve},
		{Name: "TestUnix_StreamDial", F: TestUnix_StreamDial},
		{Name: "TestUnix_StreamReadEOF", F: TestUnix_StreamReadEOF},
		{Name: "TestUnix_UnlinkOnClose", F: TestUnix_UnlinkOnClose},
	})
}
