// Code generated by "so test". DO NOT EDIT.

package main

import "solod.dev/so/testing"

func main() {
	testing.RunTests("so/math/rand", []testing.Test{
		{Name: "TestFloat64", F: TestFloat64},
		{Name: "TestGlobal", F: TestGlobal},
		{Name: "TestInt", F: TestInt},
	})
}
