// Code generated by "so test". DO NOT EDIT.

package main

import (
	"solod.dev/so/os"
	"solod.dev/so/testing"
)

func main() {
	testing.RunTests("so/encoding/json", os.Args, []testing.Test{
		{Name: "TestDecodeCollection", F: TestDecodeCollection},
		{Name: "TestDecodeScalars", F: TestDecodeScalars},
		{Name: "TestDecodeEscapes", F: TestDecodeEscapes},
		{Name: "TestDecodeKeepsSource", F: TestDecodeKeepsSource},
		{Name: "TestDecodeInvalidUTF8", F: TestDecodeInvalidUTF8},
		{Name: "TestDecodeSurrogates", F: TestDecodeSurrogates},
		{Name: "TestDecodeSkip", F: TestDecodeSkip},
		{Name: "TestDecodeNestingDepth", F: TestDecodeNestingDepth},
		{Name: "TestDecodeInvalid", F: TestDecodeInvalid},
		{Name: "TestDecodeDepth", F: TestDecodeDepth},
		{Name: "TestDecodeContainerToken", F: TestDecodeContainerToken},
		{Name: "TestDecodeWrongKind", F: TestDecodeWrongKind},
		{Name: "TestDecodeGetterKeepsFirstError", F: TestDecodeGetterKeepsFirstError},
		{Name: "TestDecodeNumberNotInt", F: TestDecodeNumberNotInt},
		{Name: "TestDecodeUint", F: TestDecodeUint},
		{Name: "TestDecodeFloatOutOfRange", F: TestDecodeFloatOutOfRange},
		{Name: "TestDecodeFreeClearsToken", F: TestDecodeFreeClearsToken},
		{Name: "TestDecodeIntOutOfRange", F: TestDecodeIntOutOfRange},
		{Name: "TestDecodeStream", F: TestDecodeStream},
		{Name: "TestDecodeStreamChunked", F: TestDecodeStreamChunked},
		{Name: "TestDecodeStreamInvalid", F: TestDecodeStreamInvalid},
		{Name: "TestDecodeTooLong", F: TestDecodeTooLong},
		{Name: "TestDecodeMaxToken", F: TestDecodeMaxToken},
		{Name: "TestDecodeTokenSizeExact", F: TestDecodeTokenSizeExact},
		{Name: "TestDecodeNumberTruncated", F: TestDecodeNumberTruncated},
		{Name: "TestDecodeBufSize", F: TestDecodeBufSize},
		{Name: "TestDecodeBufSizeWins", F: TestDecodeBufSizeWins},
		{Name: "TestDecodeReadError", F: TestDecodeReadError},
		{Name: "TestEncodeObject", F: TestEncodeObject},
		{Name: "TestEncodeNested", F: TestEncodeNested},
		{Name: "TestEncodeEscapes", F: TestEncodeEscapes},
		{Name: "TestEncodeInvalidUTF8", F: TestEncodeInvalidUTF8},
		{Name: "TestEncodeNonFinite", F: TestEncodeNonFinite},
		{Name: "TestEncodeSingleRoot", F: TestEncodeSingleRoot},
		{Name: "TestEncodeInvalid", F: TestEncodeInvalid},
		{Name: "TestEncodeDepth", F: TestEncodeDepth},
		{Name: "TestEncodeIncomplete", F: TestEncodeIncomplete},
		{Name: "TestEncodeBuffered", F: TestEncodeBuffered},
		{Name: "TestEncodeShortWrite", F: TestEncodeShortWrite},
		{Name: "TestEncodeLongToken", F: TestEncodeLongToken},
	})
}
