// Code generated by "so test". DO NOT EDIT.

package main

import "solod.dev/so/testing"

func main() {
	testing.RunTests("so/c", []testing.Test{
		{Name: "TestCString", F: TestCString},
		{Name: "TestExtern", F: TestExtern},
		{Name: "TestNumericTypes", F: TestNumericTypes},
		{Name: "TestRaw", F: TestRaw},
		{Name: "TestString", F: TestString},
		{Name: "TestVal", F: TestVal},
	})
}
