// Code generated by "so test". DO NOT EDIT.

package main

import "solod.dev/so/testing"

func main() {
	testing.RunTests("so/fmt", []testing.Test{
		{Name: "TestFprintf", F: TestFprintf},
		{Name: "TestFscanf", F: TestFscanf},
		{Name: "TestPrint", F: TestPrint},
		{Name: "TestPrintf", F: TestPrintf},
		{Name: "TestPrintln", F: TestPrintln},
		{Name: "TestSprintf", F: TestSprintf},
		{Name: "TestSscanf", F: TestSscanf},
	})
}
