// Code generated by "so test". DO NOT EDIT.

package main

import "solod.dev/so/testing"

func main() {
	testing.RunTests("so/crypto/crand", []testing.Test{
		{Name: "TestRead", F: TestRead},
		{Name: "TestRead_Empty", F: TestRead_Empty},
		{Name: "TestReader", F: TestReader},
		{Name: "TestText", F: TestText},
	})
}
