// Code generated by "so test". DO NOT EDIT.

package main

import "solod.dev/so/testing"

func main() {
	testing.RunTests("so/path", []testing.Test{
		{Name: "TestBase", F: TestBase},
		{Name: "TestClean", F: TestClean},
		{Name: "TestDir", F: TestDir},
		{Name: "TestExt", F: TestExt},
		{Name: "TestIsAbs", F: TestIsAbs},
		{Name: "TestJoin", F: TestJoin},
		{Name: "TestMatch", F: TestMatch},
		{Name: "TestSplit", F: TestSplit},
	})
}
