// Code generated by "so test". DO NOT EDIT.

package main

import "solod.dev/so/testing"

func main() {
	testing.RunTests("so/runtime", []testing.Test{
		{Name: "TestGOARCH", F: TestGOARCH},
		{Name: "TestGOOS", F: TestGOOS},
		{Name: "TestVersion", F: TestVersion},
	})
}
