// Code generated by "so test". DO NOT EDIT.

package main

import "solod.dev/so/testing"

func main() {
	testing.RunTests("so/encoding/hex", []testing.Test{
		{Name: "TestDecode", F: TestDecode},
		{Name: "TestDecodeString", F: TestDecodeString},
		{Name: "TestDump", F: TestDump},
		{Name: "TestEncode", F: TestEncode},
		{Name: "TestEncodeToString", F: TestEncodeToString},
	})
}
