// Code generated by "so test". DO NOT EDIT.

package main

import "solod.dev/so/testing"

func main() {
	testing.RunTests("so/stringslite", []testing.Test{
		{Name: "TestClone", F: TestClone},
		{Name: "TestCut", F: TestCut},
		{Name: "TestCutPrefix", F: TestCutPrefix},
		{Name: "TestCutSuffix", F: TestCutSuffix},
		{Name: "TestHasPrefix", F: TestHasPrefix},
		{Name: "TestHasSuffix", F: TestHasSuffix},
		{Name: "TestIndex", F: TestIndex},
		{Name: "TestIndexByte", F: TestIndexByte},
		{Name: "TestTrimPrefix", F: TestTrimPrefix},
		{Name: "TestTrimSuffix", F: TestTrimSuffix},
	})
}
